name: 'Setup Roc'
description: 'Download and setup the Roc compiler.'
branding:
  icon: 'download'
  color: 'purple'

inputs:
  version:
    description: 'Version of Roc to install (e.g., "nightly", "alpha4-rolling")'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download and verify Roc
      shell: bash
      run: |
        set -euo pipefail

        VERSION="${{ inputs.version }}"
        echo "Installing Roc version: $VERSION"

        # Detect OS and architecture
        OS=$(uname -s)
        ARCH=$(uname -m)

        echo "Detected OS: $OS"
        echo "Detected architecture: $ARCH"

        # Determine platform-specific values
        case "$OS" in
          Linux)
            case "$ARCH" in
              x86_64)
                PLATFORM="linux_x86_64"
                DIR_PATTERN="roc_nightly-linux_x86_64-*"
                SHA_CMD="sha256sum"
                ;;
              aarch64|arm64)
                PLATFORM="linux_arm64"
                DIR_PATTERN="roc_nightly-linux_arm64-*"
                SHA_CMD="sha256sum"
                ;;
              *)
                echo "Error: Unsupported Linux architecture: $ARCH"
                exit 1
                ;;
            esac
            ;;
          Darwin)
            case "$ARCH" in
              x86_64)
                PLATFORM="macos_x86_64"
                DIR_PATTERN="roc_nightly-macos_x86_64-*"
                SHA_CMD="shasum -a 256"
                ;;
              arm64)
                PLATFORM="macos_apple_silicon"
                DIR_PATTERN="roc_nightly-macos_apple_silicon-*"
                SHA_CMD="shasum -a 256"
                ;;
              *)
                echo "Error: Unsupported macOS architecture: $ARCH"
                exit 1
                ;;
            esac
            ;;
          *)
            echo "Error: Unsupported operating system: $OS"
            exit 1
            ;;
        esac

        # Set expected SHA256 based on version and platform
        case "$VERSION-$PLATFORM" in
          alpha3-rolling-linux_x86_64)
            EXPECTED_SHA="7fa4434b53dc8fb2ea39a2a93925de2eece569dff332365f30e7f93e819762ac"
            ;;
          alpha3-rolling-linux_arm64)
            EXPECTED_SHA="696213a44a082dfe8e3f9a6f41abef0ec390d3a75443f15081eff5532b9305a5"
            ;;
          alpha3-rolling-macos_x86_64)
            EXPECTED_SHA="5e849e461c0be0d80b9a48379699bc6fa397f81b560d98b1ec3185b4d5a3a35f"
            ;;
          alpha3-rolling-macos_apple_silicon)
            EXPECTED_SHA="66cdd1ff3a0968938ae55a1951cbdd79a41a9743310a6fa6a06f24659107593d"
            ;;
          alpha4-rolling-linux_x86_64)
            EXPECTED_SHA="96e8be05e6f7176433ada74532ff36a62b8dc44c5247a82cdf919f2dadc5178b"
            ;;
          alpha4-rolling-linux_arm64)
            EXPECTED_SHA="95558e2b5564b9f2b19fb29ad7df440d4ef7163dea571ffcd39409ef678ecccf"
            ;;
          alpha4-rolling-macos_x86_64)
            EXPECTED_SHA="e8378bdec9fbeaf8f7bae49159a7b43d42050b047375521799984311dcda7078"
            ;;
          alpha4-rolling-macos_apple_silicon)
            EXPECTED_SHA="416fbd983280eda11ac87b0947e27bf0a86d186a94baebeb71e163942bb5bd84"
            ;;
          nightly-*)
            # Nightly builds - no SHA verification
            ;;
          *)
            echo "Error: Unsupported version: $VERSION"
            echo "Supported versions: nightly, alpha3-rolling, alpha4-rolling"
            echo "Make sure your version is listed in https://github.com/roc-lang/roc/tags and try updating to"
            echo "the latest commit of the setup-roc action, see <https://github.com/roc-lang/setup-roc>."
            exit 1
            ;;
        esac

        # Download Roc
        if [[ "$VERSION" == "nightly" ]]; then
          DOWNLOAD_URL="https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-${PLATFORM}-latest.tar.gz"
          SKIP_SHA_CHECK=true
          DIR_PATTERN="roc_nightly-${PLATFORM}-*"
        else
          DOWNLOAD_URL="https://github.com/roc-lang/roc/releases/download/${VERSION}/roc-${PLATFORM}-${VERSION}.tar.gz"
          SKIP_SHA_CHECK=false
        fi

        echo "Downloading Roc for $PLATFORM..."
        curl -fsSL -o roc.tar.gz "$DOWNLOAD_URL"

        # Verify SHA256 checksum (skip for nightly releases)
        if [[ "$SKIP_SHA_CHECK" == "false" ]]; then
          echo "Verifying SHA256 checksum..."
          ACTUAL_SHA=$($SHA_CMD roc.tar.gz | awk '{print $1}')

          if [[ "$ACTUAL_SHA" != "$EXPECTED_SHA" ]]; then
            echo "Error: SHA256 checksum mismatch!"
            echo "Expected: $EXPECTED_SHA"
            echo "Actual:   $ACTUAL_SHA"
            echo "This should never happen and could mean the file is malicious. Please make a post on <https://roc.zulipchat.com> and request investigation of this incident."
            exit 1
          fi

          echo "SHA256 checksum verified successfully"
        else
          echo "Skipping SHA256 verification for nightly release"
        fi

        # Extract Roc
        echo "Extracting Roc..."
        tar -xzf roc.tar.gz
        rm roc.tar.gz

        # Find the extracted directory and add to PATH
        ROC_DIR=$(find . -maxdepth 1 -type d -name "$DIR_PATTERN" | head -n 1)
        if [[ -z "$ROC_DIR" ]]; then
          echo "Error: Could not find extracted Roc directory"
          exit 1
        fi

        echo "$GITHUB_WORKSPACE/$ROC_DIR" >> $GITHUB_PATH

        echo "Roc setup completed successfully"
