name: 'Setup Roc'
description: 'Download and setup the Roc compiler.'
branding:
  icon: 'download'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    - name: Download and verify Roc
      shell: bash
      run: |
        set -euo pipefail

        # Detect OS and architecture
        OS=$(uname -s)
        ARCH=$(uname -m)

        echo "Detected OS: $OS"
        echo "Detected architecture: $ARCH"

        # Determine platform-specific values
        case "$OS" in
          Linux)
            case "$ARCH" in
              x86_64)
                PLATFORM="linux_x86_64"
                EXPECTED_SHA="96e8be05e6f7176433ada74532ff36a62b8dc44c5247a82cdf919f2dadc5178b"
                DIR_PATTERN="roc_nightly-linux_x86_64-*"
                SHA_CMD="sha256sum"
                ;;
              aarch64|arm64)
                PLATFORM="linux_arm64"
                EXPECTED_SHA="95558e2b5564b9f2b19fb29ad7df440d4ef7163dea571ffcd39409ef678ecccf"
                DIR_PATTERN="roc_nightly-linux_arm64-*"
                SHA_CMD="sha256sum"
                ;;
              *)
                echo "Error: Unsupported Linux architecture: $ARCH"
                exit 1
                ;;
            esac
            ;;
          Darwin)
            case "$ARCH" in
              x86_64)
                PLATFORM="macos_x86_64"
                EXPECTED_SHA="e8378bdec9fbeaf8f7bae49159a7b43d42050b047375521799984311dcda7078"
                DIR_PATTERN="roc_nightly-macos_x86_64-*"
                SHA_CMD="shasum -a 256"
                ;;
              arm64)
                PLATFORM="macos_apple_silicon"
                EXPECTED_SHA="416fbd983280eda11ac87b0947e27bf0a86d186a94baebeb71e163942bb5bd84"
                DIR_PATTERN="roc_nightly-macos_apple_silicon-*"
                SHA_CMD="shasum -a 256"
                ;;
              *)
                echo "Error: Unsupported macOS architecture: $ARCH"
                exit 1
                ;;
            esac
            ;;
          *)
            echo "Error: Unsupported operating system: $OS"
            exit 1
            ;;
        esac

        # Download Roc
        DOWNLOAD_URL="https://github.com/roc-lang/roc/releases/download/alpha4-rolling/roc-${PLATFORM}-alpha4-rolling.tar.gz"
        echo "Downloading Roc for $PLATFORM..."
        curl -fsSL -o roc.tar.gz "$DOWNLOAD_URL"

        # Verify SHA256 checksum
        echo "Verifying SHA256 checksum..."
        ACTUAL_SHA=$($SHA_CMD roc.tar.gz | awk '{print $1}')

        if [[ "$ACTUAL_SHA" != "$EXPECTED_SHA" ]]; then
          echo "Error: SHA256 checksum mismatch!"
          echo "Expected: $EXPECTED_SHA"
          echo "Actual:   $ACTUAL_SHA"
          echo "This should never happen and could mean the file is malicious. Please make a post on <https://roc.zulipchat.com> and request investigation of this incident."
          exit 1
        fi

        echo "SHA256 checksum verified successfully"

        # Extract Roc
        echo "Extracting Roc..."
        tar -xzf roc.tar.gz
        rm roc.tar.gz

        # Find the extracted directory and add to PATH
        ROC_DIR=$(find . -maxdepth 1 -type d -name "$DIR_PATTERN" | head -n 1)
        if [[ -z "$ROC_DIR" ]]; then
          echo "Error: Could not find extracted Roc directory"
          exit 1
        fi

        echo "$GITHUB_WORKSPACE/$ROC_DIR" >> $GITHUB_PATH

        echo "Roc setup completed successfully"
