name: 'Setup Roc'
description: 'Download and setup the Roc compiler.'
branding:
  icon: 'download'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    - name: Download and verify Roc
      shell: bash
      run: |
        set -euo pipefail

        # Check if running on Linux x86_64
        if [[ "$OSTYPE" != "linux-gnu"* ]]; then
          echo "Error: This action currently only supports Linux"
          exit 1
        fi

        if [[ "$(uname -m)" != "x86_64" ]]; then
          echo "Error: This action currently only supports x86_64 architecture"
          exit 1
        fi

        # Download Roc
        echo "Downloading Roc for Linux x86_64..."
        curl -fsSL -o roc.tar.gz https://github.com/roc-lang/roc/releases/download/alpha4-rolling/roc-linux_x86_64-alpha4-rolling.tar.gz

        # Verify SHA256 checksum
        echo "Verifying SHA256 checksum..."
        EXPECTED_SHA="96e8be05e6f7176433ada74532ff36a62b8dc44c5247a82cdf919f2dadc5178b"
        ACTUAL_SHA=$(sha256sum roc.tar.gz | awk '{print $1}')

        if [[ "$ACTUAL_SHA" != "$EXPECTED_SHA" ]]; then
          echo "Error: SHA256 checksum mismatch!"
          echo "Expected: $EXPECTED_SHA"
          echo "Actual:   $ACTUAL_SHA"
          echo "This should never happen and could mean the file is malicious. Please make a post on <https://roc.zulipchat.com> and request investigation of this incident."
          exit 1
        fi

        echo "SHA256 checksum verified successfully"

        # Extract Roc
        echo "Extracting Roc..."
        tar -xzf roc.tar.gz
        rm roc.tar.gz

        # Find the extracted directory and add to PATH
        ROC_DIR=$(find . -maxdepth 1 -type d -name "roc_nightly-linux_x86_64-*" | head -n 1)
        if [[ -z "$ROC_DIR" ]]; then
          echo "Error: Could not find extracted Roc directory"
          exit 1
        fi

        echo "$GITHUB_WORKSPACE/$ROC_DIR" >> $GITHUB_PATH

        echo "Roc setup completed successfully"
